### ISSUE TITLE
Quits after radio stream changes in active Queue

### ISSUE THREAD

**Issue by Narrat** [eworm-de/mpd-notification#7]
I noticed the following behaviour:
I have one set a Queue just with radio streams. And if I switch between the streams mpd-notification quits every time.
With local files everything is normal aka it will be running until I clear the Queue.
Can this behaviour be changed or is it due to the streams?

Setup:
*mpd (not started on boot; manually via systemctl --user)
*mpd-notification (manually from a shell after mpd is running. I did try the systemd user service, but it wasn't working the way I hoped)

**Comment by eworm-de** [comment]
Any terminal output? Any more information when started with `-vv`?

I never tried to play streams with mpd... Looks like it's time to change that. ;)

**Comment by Narrat** [comment]
None output at all

>~ $ mpd-notification&
[1] 29143
~ $ 
[1]  + done       mpd-notification
~ $ mpd-notification 
~ $ mpd-notification -vv
mpd-notification: mpd-notification v0.7.1 (compiled: Oct 13 2015, 19:44:32)
Exiting...

**Comment by eworm-de** [comment]
There are two possible code pathes to break the while loop and exit:
* `mpd-notification` receives a signal and sets `doexit++`
* `mpd_run_idle_mask` returns `0`, which indicates an error: [libmpdclient documentation](http://libmpdclient.sourcearchive.com/documentation/2.3/idle_8h_7284fb29f833fcce46e9fed88931d2aa.html)

I suppose the latter is the case - otherwise you would see a message: `Received signal ..., preparing exit.`
Probably this is a bug in `libmpdclient`...

**Comment by Narrat** [comment]
I can confirm, this is working
Thanks for fixing it :)
